# ASP.NET Core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: AzureRmWebAppDeployment@3
  inputs:
    azureSubscription: 'Free Trial'
    WebAppName: 'Simple-Chat-Service'
    Package: $(System.ArtifactsDirectory)/**/*.zip